/**
 * The two configurations the benchmark compares, and the overlay that builds one.
 *
 * Both arms boot the same shipped `headless` profile. They differ only by a
 * `--patch` overlay, which the loader applies through the same path a bundle
 * uses — so the plugins in the "on" arm are mounted the way they are mounted for
 * real, and the "off" arm is the untouched shipped profile rather than a
 * hand-stripped copy of it.
 *
 * The "on" arm lists exactly the local bundles the desktop profile mounts for
 * this work, minus two:
 *
 * - `dsh-workspace-mcp` registers MCP servers a workspace declares in
 *   `.mcp.json`. The fixtures declare none, so it is inert here, and including
 *   an inert plugin would only invite the reading that it was part of the
 *   intervention.
 * - `dsh-edit-feedback` was unmounted from the desktop profile on 2026-10-03
 *   after its prediction failed, so it is not part of what is being compared.
 *   It can still be added deliberately with `--variant edit-feedback`.
 *
 * @module bench/variants
 */

import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = fileURLToPath(new URL('..', import.meta.url))

/** The local plugin bundles this repository ships, by package directory name. */
export const LOCAL_BUNDLES = [
  'dsh-guidance-pack',
  'dsh-apply-patch',
  'dsh-verify-on-edit',
  'dsh-check-claims',
  'dsh-compaction-todo',
  'dsh-approval-memory',
]

/** Every variant, as the plugin packages it mounts. `off` mounts none. */
export const VARIANTS = {
  off: [],
  on: LOCAL_BUNDLES,
  'edit-feedback': [...LOCAL_BUNDLES, 'dsh-edit-feedback'],
}

/**
 * The entry file a plugin package exports, read from its own manifest.
 * @param pkg - the package directory name under `packages/`.
 * @param prefix - where `packages/` is mounted, for a container run whose paths
 *   differ from the host's. Omit for a host run.
 * @returns the absolute path to the entry file.
 */
export function entryOf(pkg, prefix) {
  const main = JSON.parse(readFileSync(join(ROOT, 'packages', pkg, 'package.json'), 'utf8')).main ?? 'src/index.ts'
  return prefix === undefined
    ? join(ROOT, 'packages', pkg, main)
    : join(prefix, pkg, main)
}

/**
 * Quote a scalar for the overlay YAML.
 * @param value - the raw string.
 * @returns a single-quoted YAML scalar.
 */
function yaml(value) {
  return `'${String(value).replace(/'/g, "''")}'`
}

/**
 * Build the `--patch` overlay that mounts a variant's plugins.
 * @param variant - a key of {@link VARIANTS}.
 * @param prefix - where `packages/` is mounted inside a container run; omit for
 *   a host run, where the overlay points at this checkout.
 * @returns the overlay document, or an empty string when the variant mounts nothing.
 */
export function overlayFor(variant, prefix) {
  const packages = VARIANTS[variant]
  if (packages === undefined) throw new Error(`unknown variant: ${variant}`)
  if (packages.length === 0) return '# variant "off": no overlay, the shipped profile as it ships\n'
  const rows = packages
    .map(pkg => `    - id: bench-${pkg.replace(/^dsh-/, '')}\n      name: ${yaml(entryOf(pkg, prefix))}`)
    .join('\n')
  return `# generated by bench/run.mjs for variant "${variant}"\n- insert:\n${rows}\n`
}
